### Register POST

POST http://localhost:9001/register
Accept: application/json
Content-Type: application/json

{
    "name" :"tono",
    "username" :"tono",
    "password" :"tono"
}

### Login 
POST http://localhost:9001/login
Accept: application/json
Content-Type: application/json

{
    "username" :"billy",
    "password" :"billy"
}

### send message
POST  http://localhost:9000/users/message
Accept: application/json
Content-Type: application/json

{
    "date" :"2023-03-14T00:00:00Z",
    "message":"hallo test 18",
    "receiver" :"bima"
}

### GET  Publisc and send
GET  http://localhost:9001/users/publisher/sender
Accept: application/json




### send messageTest
POST  http://localhost:9000/users/messageTest
Accept: application/json
Content-Type: application/json

{
    "date" :"2023-03-14T00:00:00Z",
    "message":"hallo test 1",
    "receiver" :"bima"
}

### Message show sender and last message
GET http://localhost:9000/users/message
Accept: application/json

### Read message from sender
GET http://localhost:9000/users/read?sender=billy&pageSize=10&page=0
Accept: application/json

### Setread 
POST http://localhost:9000/users/setread
Accept: application/json
Content-Type: application/json

{
    "message_id" :8,
    "sender_id":1
}

### Logout
GET http://localhost:9001/users/logout
Accept: application/json